Added 10 Seconds Ninja X
gamer-os/steam-tweaks pull request #13
Opened 2020-10-11 16:44 UTC by rshamsnejad

There was some serious lag with Proton 5 that completely disappeared with Proton 4.11.

2020-10-12 14:38 UTC, alkazar requested changes

2020-10-12 14:38 UTC, alkazar commented on steam-tweaks.yaml
> +"435790": # 10 Seconds Ninja X
Minor typo: the name of the game is "10 Second Ninja X".

2020-10-12 18:43 UTC, rshamsnejad commented on steam-tweaks.yaml
> +"435790": # 10 Seconds Ninja X
Ah damn, should have copied/pasted ! It's now fixed.

2020-10-13 02:08 UTC, alkazar approved these changes

2020-10-13 02:08 UTC, merged