Proton Whitelisting
gamer-os/steam-tweaks pull request #16
Opened 2021-01-02 21:04 UTC by daddeltrotter

Hello,
I added the games I tested in the past two months.
In the past days, I changed my testing approach and did it first with the latest stable version, 
hence majority of test were done on the latest development verion (which turned out to be quite stable).
Thanks for reviewing. If I missed something or did something wrong, please let me know.
Best regards,
Daddeltrotter

2021-01-02 22:39 UTC, alkazar requested changes

2021-01-02 22:39 UTC, alkazar commented on steam-tweaks.yaml
> +"238930": # 7 Grand Steps, Step 1: What Ancients Begat
The game name appears to be "7 Grand Steps: What Ancients Begat" according to Steam.

2021-01-02 22:39 UTC, alkazar commented on steam-tweaks.yaml
> +  compat_tool: proton_51
Is this supposed to be `proton_513`? I don't think there is a `proton_51`.

2021-01-02 22:39 UTC, alkazar commented on steam-tweaks.yaml
> +“829590”: # Crying Suns
Looks like the ID should be "873940".

2021-01-02 22:39 UTC, alkazar commented on steam-tweaks.yaml
> +“829590”: # Crying Suns
The quote characters are not correct.

2021-01-02 22:39 UTC, alkazar commented on steam-tweaks.yaml
> +“829590”: # Cryofall (Beta Proton Release of devs)
quote characters are not correct, but let's wait until this is working with the full release and not just the beta.

2021-01-02 22:39 UTC, alkazar commented on steam-tweaks.yaml
> +“928840”: # Cybarian: The Time Travelling Warrior
quotes

2021-01-02 22:39 UTC, alkazar commented on steam-tweaks.yaml
> +“405500”: # Dangerous Golf
quotes

2021-01-02 22:39 UTC, alkazar commented on steam-tweaks.yaml
> +  compat_tool: proton_51
`proton_513`?

2021-01-02 22:39 UTC, alkazar commented on steam-tweaks.yaml
> +  compat_tool: proton_51
`proton_513`?

2021-01-03 13:13 UTC, daddeltrotter commented on steam-tweaks.yaml
> +"238930": # 7 Grand Steps, Step 1: What Ancients Begat
Mmmh..right. In my Proton list it shows with "step1". Strange...Chenged it

2021-01-03 13:21 UTC, daddeltrotter commented on steam-tweaks.yaml
> +  compat_tool: proton_51
5

2021-01-03 13:22 UTC, daddeltrotter commented on steam-tweaks.yaml
> +“829590”: # Crying Suns
Right...Copy&paste :(

2021-01-03 13:23 UTC, daddeltrotter commented on steam-tweaks.yaml
> +“829590”: # Crying Suns
Damn...

2021-01-03 13:23 UTC, daddeltrotter commented on steam-tweaks.yaml
> +“829590”: # Cryofall (Beta Proton Release of devs)
I commented the game and keep watching it.

2021-01-03 13:23 UTC, daddeltrotter commented on steam-tweaks.yaml
> +“928840”: # Cybarian: The Time Travelling Warrior
Corrected

2021-01-03 13:24 UTC, daddeltrotter commented on steam-tweaks.yaml
> +“405500”: # Dangerous Golf
Corrected

2021-01-03 13:25 UTC, daddeltrotter commented on steam-tweaks.yaml
> +  compat_tool: proton_51
5

2021-01-03 13:25 UTC, daddeltrotter commented on steam-tweaks.yaml
> +  compat_tool: proton_51
5

2021-01-03 13:37 UTC, daddeltrotter commented
Made all the changes. Sorry for my inattentions...

2021-01-03 13:42 UTC, alkazar requested changes
Thanks for the fixes! Just one more small thing.

2021-01-03 13:42 UTC, alkazar commented on steam-tweaks.yaml
> +# "829590": # Cryofall (Beta Proton Release of devs)
Please remove entirely. We can add it again when it is ready.

2021-01-03 14:59 UTC, daddeltrotter commented on steam-tweaks.yaml
> +# "829590": # Cryofall (Beta Proton Release of devs)
Done

2021-01-03 23:44 UTC, merged

2021-01-03 23:44 UTC, alkazar commented
Nice work, thanks!