A bunch of tested proton games
gamer-os/steam-tweaks pull request #20
Opened 2021-02-13 09:53 UTC by daddeltrotter

2021-03-29 02:55 UTC, alkazar commented
@daddeltrotter Sorry for the delay. It seems there are some conflicts, could you please merge in latest master and resolve them? Thank you!

2021-03-29 07:14 UTC, daddeltrotter commented
@alkazar: I've resolved the conflicts. Hope everything is fine now.

2021-03-30 01:55 UTC, alkazar requested changes

2021-03-30 01:55 UTC, alkazar commented on steam-tweaks.yaml
> +"1047220": # Frog Detective 2 The_Case of the Invisible Wizard
title should be: "Frog Detective 2: The Case of the Invisible Wizard"

2021-03-30 01:55 UTC, alkazar commented on steam-tweaks.yaml
> +"405970": # Flat Kingdom Papers Cut Edition
title should be: "Flat Kingdom Paper's Cut Edition"

2021-03-30 01:55 UTC, alkazar commented on steam-tweaks.yaml
> +"1142500": # Fun with Ragdolls The Game
title should be: "Fun with Ragdolls: The Game"

2021-03-30 01:55 UTC, alkazar commented on steam-tweaks.yaml
> +"914010": # TrainStation Renovation
title should be: "Train Station Renovation"

2021-03-30 01:55 UTC, alkazar commented on steam-tweaks.yaml
> +"774241": # Warhammer Chaosbane
title should be: "Warhammer: Chaosbane"

2021-03-30 01:55 UTC, alkazar commented on steam-tweaks.yaml
> +"690640": # Trine 4: The Nightmare Prince
Oops, I must have copied the Trine 3 app id. Nice catch!

2021-03-30 01:55 UTC, alkazar commented on steam-tweaks.yaml
> +  steam-input: enabled
It should actually be "steam_input", not "steam-input". But, "steam_input: enabled" has no effect on games run with proton. Steam Input is always enabled for Proton games. So this line should be removed.

2021-03-30 01:55 UTC, alkazar commented on steam-tweaks.yaml
> -"1142100": # WWE 2K BATTLEGROUNDS
Oops, my bad.

2021-03-30 01:55 UTC, alkazar commented on steam-tweaks.yaml
> +"1142100": # WWE 2K BATTLEGROUNDS
Thanks!

2021-03-30 06:52 UTC, daddeltrotter commented on steam-tweaks.yaml
> +"405970": # Flat Kingdom Papers Cut Edition
Thanks. Changed it.

2021-03-30 06:53 UTC, daddeltrotter commented on steam-tweaks.yaml
> +"1047220": # Frog Detective 2 The_Case of the Invisible Wizard
Thanks changed it.

2021-03-30 06:53 UTC, daddeltrotter commented on steam-tweaks.yaml
> +"1142500": # Fun with Ragdolls The Game
Thanks. Changed it.

2021-03-30 06:53 UTC, daddeltrotter commented on steam-tweaks.yaml
> +"914010": # TrainStation Renovation
Thanks. Changed it.

2021-03-30 06:54 UTC, daddeltrotter commented on steam-tweaks.yaml
> +"774241": # Warhammer Chaosbane
Thanks. changed it.

2021-03-30 07:03 UTC, daddeltrotter commented on steam-tweaks.yaml
> +  steam-input: enabled
I will remove it. 
But I'm pretty sure that only with Steam Input enabled the controller was detected. 
I found similar case with "NiGHTS Into Dreams".
I will check again the two games.

2021-03-31 00:07 UTC, merged