March list of tested proton games
gamer-os/steam-tweaks pull request #24
Opened 2021-04-01 08:22 UTC by daddeltrotter

@alkazar:
Testing is progressing very well. So sorry that there is already a new list from my side :)
I updated also the proton release for a few games I have tested and where also protondb.com indicates that the new version causes less issues than the old ones:
- LEGO Batman 3: Beyond Gotham
- Jurassic World Evolution
- Heave Ho
Hope I have catched this time all typos.

2021-04-01 22:24 UTC, alkazar requested changes

2021-04-01 22:24 UTC, alkazar commented on steam-tweaks.yaml
> +    - exec: mv KidGame/Config/KidEngine.ini KidGame/Config/KidEngine.ini.bak && sed '/\[XAudio2.XAudio2Device\]/{n;N;N;N;N;N;d}' KidGame/Config/KidEngine.ini.bak | sed '/\[XAudio2.XAudio2Device\]/'a'
will this work if run multiple times?

2021-04-01 22:24 UTC, alkazar commented on steam-tweaks.yaml
> +  launch_options: %command% -onethread
this will result in a syntax error due to the string starting with `%`.

You don't actually need the `%command%`. Just `-onethread` will work.

2021-04-01 22:24 UTC, alkazar commented on steam-tweaks.yaml
> +"299380: # Masquerade: The Baubles of Doom
missing a quote here

2021-04-01 23:24 UTC, daddeltrotter commented on steam-tweaks.yaml
> +    - exec: mv KidGame/Config/KidEngine.ini KidGame/Config/KidEngine.ini.bak && sed '/\[XAudio2.XAudio2Device\]/{n;N;N;N;N;N;d}' KidGame/Config/KidEngine.ini.bak | sed '/\[XAudio2.XAudio2Device\]/'a'
Yes, it will.
1. Existing ini-File will be renamed.
2. sed looks for [XAudio2.XAudio2Device\] in the ini file; deletes the contents of this section (6 lines) and inserts the correct configuration into this section.
When you run the command again, it always replaces the same 6 lines.

2021-04-01 23:28 UTC, daddeltrotter commented on steam-tweaks.yaml
> +"299380: # Masquerade: The Baubles of Doom
Thanks. I added the quote.

2021-04-01 23:45 UTC, daddeltrotter commented on steam-tweaks.yaml
> +  launch_options: %command% -onethread
OK. 
But just for my curiosity to understand, I found several entried:
  launch_options: '%command% -screen-fullscreen 0'
  launch_options: '%command%'
  launch_options: SDL_AUDIODRIVER="directsound" %command%
  launch_options: mv jetsetradio.exe jsrsetup.exe; %command%
  launch_options: '%command% -nohmd'
  launch_options: --skip-intro

I'm a little bit confused:
If the launch options must come before the game is launched, I have to add the %command% at the end?
If there is only a parameter to be passed. I can ommit the %command% in steamtweaks.yaml and staemtweaks takes care on the correct setting of the launch parameter and adds %command% automatcally?
But I could also put '%command% -onethread'? Or are these existing entries (like '%command% -nohmd'
) wrong?  
Can you please explain?

2021-04-02 01:05 UTC, alkazar commented on steam-tweaks.yaml
> +  launch_options: %command% -onethread
> OK.
> But just for my curiosity to understand, I found several entried:
> launch_options: '%command% -screen-fullscreen 0'
> launch_options: '%command%'
> launch_options: SDL_AUDIODRIVER="directsound" %command%
> launch_options: mv jetsetradio.exe jsrsetup.exe; %command%
> launch_options: '%command% -nohmd'
> launch_options: --skip-intro
> 
> I'm a little bit confused:
> If the launch options must come before the game is launched, I have to add the %command% at the end?
> If there is only a parameter to be passed. I can ommit the %command% in steamtweaks.yaml and staemtweaks takes care on the correct setting of the launch parameter and adds %command% automatcally?
> But I could also put '%command% -onethread'? Or are these existing entries (like '%command% -nohmd'
> ) wrong?
> Can you please explain?

I guess I have been inconsistent!

Yes, if you do not specify '%command%' Steam just puts it at the front automatically.

If you do start with %command% then the whole things needs to be in quotes otherwise yaml will blow up.

The one entry with just %command% is there so that the previously set launch options which no longer work are removed.

2021-04-02 07:52 UTC, daddeltrotter commented on steam-tweaks.yaml
> +  launch_options: %command% -onethread
Thanks for the explanation!

2021-04-04 13:35 UTC, alkazar commented
Thank you for your efforts!

2021-04-04 13:35 UTC, merged