Enhance load_steam_config to fix issue #2
gamer-os/steam-tweaks pull request #25
Opened 2021-04-10 11:00 UTC by DaedalusHyperboreus

2021-04-14 11:46 UTC, alkazar requested changes

2021-04-14 11:46 UTC, alkazar commented on steam-config
> +			if not steam['CompatToolMapping'][game]['name'] and not steam['CompatToolMapping'][game]['config']:
if there are entries that do not contain 'config' or 'name', then this fails.
You have to first check that a key exists with if key in dict
e.g. if 'config' in steam['CompatToolMapping'][game]

I recommend loading the name and config values into a variable, defaulting to None if they don't exist and use those variables in the if statement.

2021-05-09 20:17 UTC, DaedalusHyperboreus commented
I've added an additional if clause to prevent the NameError exception.
Tested with my own config.vdf from the gaming machine.

2021-05-10 08:02 UTC, sharkwouter commented on steam-config
> +                if 'name' in steam['CompatToolMapping'][game] and 'config' in steam['CompatToolMapping'][game]:
It looks like the spacing is off and the for loop has been disabled now. I did not test it, though, but it doesn't look right.

2021-05-10 10:04 UTC, DaedalusHyperboreus commented on steam-config
> +                if 'name' in steam['CompatToolMapping'][game] and 'config' in steam['CompatToolMapping'][game]:
Uff, thanks for noticing. Somehow this evaded me... 🤦

2021-05-11 12:33 UTC, alkazar requested changes

2021-05-11 12:33 UTC, alkazar commented on steam-config
> +				if not steam['CompatToolMapping'][game]['name'] and not steam['CompatToolMapping'][game]['config']:
This is a bit confusing when combined with the condition above. Maybe it would be clearer to be more explicit and check for `steam['CompatToolMapping'][game]['name'] == ''` and `steam['CompatToolMapping'][game]['config'] == ''`

2021-05-15 14:53 UTC, alkazar commented
Nice work, thanks!

2021-05-15 14:54 UTC, merged