Fix last play time and other keys in the shortcuts.vdf file
gamer-os/steam-tweaks pull request #26
Opened 2021-04-18 22:27 UTC by Samsagax

This changes the base used for a new shortcut entry.
It tries to match the `appid` of the shortcut with existing ones by Steam and if it succeeds it is used as a base for the entry. It's meant to fix #15 

This still discards any shortcut not specified in any yaml file.

2021-04-19 15:39 UTC, Samsagax commented
This also potentially fixes #3 as removes `pycrc` as an import in favor of `binascii`

2021-04-22 02:13 UTC, alkazar requested changes

2021-04-22 02:13 UTC, alkazar commented on steam-shortcuts
> +        data = yaml.load(y, Loader=yaml.FullLoader)
Oops, this now means only a single shortcut file will be loaded.
When I tested this out, it is indeed the case that multiple yaml files do not get loaded.

Could the diff be simplified? There seems to be a lot of code moved around and it looks like it is causing logic issues.

2021-04-22 02:13 UTC, alkazar commented on steam-shortcuts
> +        if int(sc[s]['appid']) == int(app_id):
While testing, I experienced an error here. 'appid' was not a key. Not sure how that can happen (probably a bad shortcut entry in the vdf), but we should probably add `'appid' in sc[s] and ...` to the condition.

2021-04-22 03:24 UTC, Samsagax commented on steam-shortcuts
> +        if int(sc[s]['appid']) == int(app_id):
Change added in next commit

2021-04-22 03:29 UTC, Samsagax commented on steam-shortcuts
> +        data = yaml.load(y, Loader=yaml.FullLoader)
Yeah, the diff is weird how it ended up, but works for me on more than one yaml file. Just load one shortcut set at the beginning.

2021-04-22 20:14 UTC, alkazar requested changes

2021-04-22 20:14 UTC, alkazar commented on steam-shortcuts
> +        data = data + dd
This doesn't work when there are yaml files with a single shortcut in it. I get this error:
```
Traceback (most recent call last):
  File "/home/alesh/test.py", line 128, in <module>
    data = data + dd
TypeError: can only concatenate list (not "dict") to list
```

I think you need to either preprocess the yaml files with the code on lines 148-156 or reload the yaml files for each steam user.

2021-04-23 02:02 UTC, merged